//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4016.
// 
#pragma warning disable 1591

namespace WindowsApplication1.GSPAclWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GssAclMonitorSoap", Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssAclBaseResult))]
    public partial class GssAclMonitor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckConnectivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAclForUrlsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAclChangesSinceTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResolveSPGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListsWithInheritingRoleAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListItemsWithInheritingRoleAssignmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GssAclMonitor() {
            this.Url = global::WindowsApplication1.Properties.Settings.Default.Verify_Installation_GSPAclWS_GssAclMonitor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckConnectivityCompletedEventHandler CheckConnectivityCompleted;
        
        /// <remarks/>
        public event GetAclForUrlsCompletedEventHandler GetAclForUrlsCompleted;
        
        /// <remarks/>
        public event GetAclChangesSinceTokenCompletedEventHandler GetAclChangesSinceTokenCompleted;
        
        /// <remarks/>
        public event ResolveSPGroupCompletedEventHandler ResolveSPGroupCompleted;
        
        /// <remarks/>
        public event GetListsWithInheritingRoleAssignmentsCompletedEventHandler GetListsWithInheritingRoleAssignmentsCompleted;
        
        /// <remarks/>
        public event GetListItemsWithInheritingRoleAssignmentsCompletedEventHandler GetListItemsWithInheritingRoleAssignmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/CheckConnectivity", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckConnectivity() {
            object[] results = this.Invoke("CheckConnectivity", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckConnectivityAsync() {
            this.CheckConnectivityAsync(null);
        }
        
        /// <remarks/>
        public void CheckConnectivityAsync(object userState) {
            if ((this.CheckConnectivityOperationCompleted == null)) {
                this.CheckConnectivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckConnectivityOperationCompleted);
            }
            this.InvokeAsync("CheckConnectivity", new object[0], this.CheckConnectivityOperationCompleted, userState);
        }
        
        private void OnCheckConnectivityOperationCompleted(object arg) {
            if ((this.CheckConnectivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckConnectivityCompleted(this, new CheckConnectivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/GetAclForUrls", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GssGetAclForUrlsResult GetAclForUrls(string[] urls) {
            object[] results = this.Invoke("GetAclForUrls", new object[] {
                        urls});
            return ((GssGetAclForUrlsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAclForUrlsAsync(string[] urls) {
            this.GetAclForUrlsAsync(urls, null);
        }
        
        /// <remarks/>
        public void GetAclForUrlsAsync(string[] urls, object userState) {
            if ((this.GetAclForUrlsOperationCompleted == null)) {
                this.GetAclForUrlsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAclForUrlsOperationCompleted);
            }
            this.InvokeAsync("GetAclForUrls", new object[] {
                        urls}, this.GetAclForUrlsOperationCompleted, userState);
        }
        
        private void OnGetAclForUrlsOperationCompleted(object arg) {
            if ((this.GetAclForUrlsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAclForUrlsCompleted(this, new GetAclForUrlsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/GetAclChangesSinceTok" +
            "en", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GssGetAclChangesSinceTokenResult GetAclChangesSinceToken(string fromChangeToken, string toChangeToken) {
            object[] results = this.Invoke("GetAclChangesSinceToken", new object[] {
                        fromChangeToken,
                        toChangeToken});
            return ((GssGetAclChangesSinceTokenResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAclChangesSinceTokenAsync(string fromChangeToken, string toChangeToken) {
            this.GetAclChangesSinceTokenAsync(fromChangeToken, toChangeToken, null);
        }
        
        /// <remarks/>
        public void GetAclChangesSinceTokenAsync(string fromChangeToken, string toChangeToken, object userState) {
            if ((this.GetAclChangesSinceTokenOperationCompleted == null)) {
                this.GetAclChangesSinceTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAclChangesSinceTokenOperationCompleted);
            }
            this.InvokeAsync("GetAclChangesSinceToken", new object[] {
                        fromChangeToken,
                        toChangeToken}, this.GetAclChangesSinceTokenOperationCompleted, userState);
        }
        
        private void OnGetAclChangesSinceTokenOperationCompleted(object arg) {
            if ((this.GetAclChangesSinceTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAclChangesSinceTokenCompleted(this, new GetAclChangesSinceTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/ResolveSPGroup", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GssResolveSPGroupResult ResolveSPGroup(string[] groupId) {
            object[] results = this.Invoke("ResolveSPGroup", new object[] {
                        groupId});
            return ((GssResolveSPGroupResult)(results[0]));
        }
        
        /// <remarks/>
        public void ResolveSPGroupAsync(string[] groupId) {
            this.ResolveSPGroupAsync(groupId, null);
        }
        
        /// <remarks/>
        public void ResolveSPGroupAsync(string[] groupId, object userState) {
            if ((this.ResolveSPGroupOperationCompleted == null)) {
                this.ResolveSPGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResolveSPGroupOperationCompleted);
            }
            this.InvokeAsync("ResolveSPGroup", new object[] {
                        groupId}, this.ResolveSPGroupOperationCompleted, userState);
        }
        
        private void OnResolveSPGroupOperationCompleted(object arg) {
            if ((this.ResolveSPGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResolveSPGroupCompleted(this, new ResolveSPGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/GetListsWithInheritin" +
            "gRoleAssignments", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetListsWithInheritingRoleAssignments() {
            object[] results = this.Invoke("GetListsWithInheritingRoleAssignments", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListsWithInheritingRoleAssignmentsAsync() {
            this.GetListsWithInheritingRoleAssignmentsAsync(null);
        }
        
        /// <remarks/>
        public void GetListsWithInheritingRoleAssignmentsAsync(object userState) {
            if ((this.GetListsWithInheritingRoleAssignmentsOperationCompleted == null)) {
                this.GetListsWithInheritingRoleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListsWithInheritingRoleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("GetListsWithInheritingRoleAssignments", new object[0], this.GetListsWithInheritingRoleAssignmentsOperationCompleted, userState);
        }
        
        private void OnGetListsWithInheritingRoleAssignmentsOperationCompleted(object arg) {
            if ((this.GetListsWithInheritingRoleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListsWithInheritingRoleAssignmentsCompleted(this, new GetListsWithInheritingRoleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssAcl.generated.sharepoint.connector.enterprise.google.com/GetListItemsWithInher" +
            "itingRoleAssignments", RequestNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GssGetListItemsWithInheritingRoleAssignments GetListItemsWithInheritingRoleAssignments(string listGuId, int rowLimit, int lastItemId) {
            object[] results = this.Invoke("GetListItemsWithInheritingRoleAssignments", new object[] {
                        listGuId,
                        rowLimit,
                        lastItemId});
            return ((GssGetListItemsWithInheritingRoleAssignments)(results[0]));
        }
        
        /// <remarks/>
        public void GetListItemsWithInheritingRoleAssignmentsAsync(string listGuId, int rowLimit, int lastItemId) {
            this.GetListItemsWithInheritingRoleAssignmentsAsync(listGuId, rowLimit, lastItemId, null);
        }
        
        /// <remarks/>
        public void GetListItemsWithInheritingRoleAssignmentsAsync(string listGuId, int rowLimit, int lastItemId, object userState) {
            if ((this.GetListItemsWithInheritingRoleAssignmentsOperationCompleted == null)) {
                this.GetListItemsWithInheritingRoleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListItemsWithInheritingRoleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("GetListItemsWithInheritingRoleAssignments", new object[] {
                        listGuId,
                        rowLimit,
                        lastItemId}, this.GetListItemsWithInheritingRoleAssignmentsOperationCompleted, userState);
        }
        
        private void OnGetListItemsWithInheritingRoleAssignmentsOperationCompleted(object arg) {
            if ((this.GetListItemsWithInheritingRoleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListItemsWithInheritingRoleAssignmentsCompleted(this, new GetListItemsWithInheritingRoleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetAclForUrlsResult : GssAclBaseResult {
        
        private GssAcl[] allAclsField;
        
        /// <remarks/>
        public GssAcl[] AllAcls {
            get {
                return this.allAclsField;
            }
            set {
                this.allAclsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAcl {
        
        private string entityUrlField;
        
        private string ownerField;
        
        private GssAce[] allAceField;
        
        private string logMessageField;
        
        /// <remarks/>
        public string EntityUrl {
            get {
                return this.entityUrlField;
            }
            set {
                this.entityUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public GssAce[] AllAce {
            get {
                return this.allAceField;
            }
            set {
                this.allAceField = value;
            }
        }
        
        /// <remarks/>
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAce {
        
        private GssPrincipal principalField;
        
        private GssSharepointPermission permissionField;
        
        /// <remarks/>
        public GssPrincipal Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public GssSharepointPermission Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssPrincipal {
        
        private string nameField;
        
        private PrincipalType typeField;
        
        private GssPrincipal[] membersField;
        
        private string logMessageField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public PrincipalType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public GssPrincipal[] Members {
            get {
                return this.membersField;
            }
            set {
                this.membersField = value;
            }
        }
        
        /// <remarks/>
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum PrincipalType {
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        DOMAINGROUP,
        
        /// <remarks/>
        SPGROUP,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAclChange {
        
        private ObjectType changedObjectField;
        
        private SPChangeType changeTypeField;
        
        private string hintField;
        
        private bool isEffectiveInCurrentWebField;
        
        /// <remarks/>
        public ObjectType ChangedObject {
            get {
                return this.changedObjectField;
            }
            set {
                this.changedObjectField = value;
            }
        }
        
        /// <remarks/>
        public SPChangeType ChangeType {
            get {
                return this.changeTypeField;
            }
            set {
                this.changeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEffectiveInCurrentWeb {
            get {
                return this.isEffectiveInCurrentWebField;
            }
            set {
                this.isEffectiveInCurrentWebField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum ObjectType {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        SECURITY_POLICY,
        
        /// <remarks/>
        ADMINISTRATORS,
        
        /// <remarks/>
        GROUP,
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        WEB,
        
        /// <remarks/>
        LIST,
        
        /// <remarks/>
        ITEM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum SPChangeType {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Rename,
        
        /// <remarks/>
        MoveAway,
        
        /// <remarks/>
        MoveInto,
        
        /// <remarks/>
        Restore,
        
        /// <remarks/>
        RoleAdd,
        
        /// <remarks/>
        RoleDelete,
        
        /// <remarks/>
        RoleUpdate,
        
        /// <remarks/>
        AssignmentAdd,
        
        /// <remarks/>
        AssignmentDelete,
        
        /// <remarks/>
        MemberAdd,
        
        /// <remarks/>
        MemberDelete,
        
        /// <remarks/>
        SystemUpdate,
        
        /// <remarks/>
        Navigation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAclChangeCollection {
        
        private string changeTokenField;
        
        private GssAclChange[] changesField;
        
        private string logMessageField;
        
        /// <remarks/>
        public string ChangeToken {
            get {
                return this.changeTokenField;
            }
            set {
                this.changeTokenField = value;
            }
        }
        
        /// <remarks/>
        public GssAclChange[] Changes {
            get {
                return this.changesField;
            }
            set {
                this.changesField = value;
            }
        }
        
        /// <remarks/>
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssSharepointPermission {
        
        private string[] allowedPermissionsField;
        
        private string[] deniedPermissionField;
        
        /// <remarks/>
        public string[] AllowedPermissions {
            get {
                return this.allowedPermissionsField;
            }
            set {
                this.allowedPermissionsField = value;
            }
        }
        
        /// <remarks/>
        public string[] DeniedPermission {
            get {
                return this.deniedPermissionField;
            }
            set {
                this.deniedPermissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetListItemsWithInheritingRoleAssignments))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssResolveSPGroupResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetAclChangesSinceTokenResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetAclForUrlsResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public abstract partial class GssAclBaseResult {
        
        private string siteCollectionUrlField;
        
        private System.Guid siteCollectionGuidField;
        
        private string logMessageField;
        
        /// <remarks/>
        public string SiteCollectionUrl {
            get {
                return this.siteCollectionUrlField;
            }
            set {
                this.siteCollectionUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SiteCollectionGuid {
            get {
                return this.siteCollectionGuidField;
            }
            set {
                this.siteCollectionGuidField = value;
            }
        }
        
        /// <remarks/>
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetListItemsWithInheritingRoleAssignments : GssAclBaseResult {
        
        private string docXmlField;
        
        private bool moreDocsField;
        
        private int lastIdVisitedField;
        
        /// <remarks/>
        public string DocXml {
            get {
                return this.docXmlField;
            }
            set {
                this.docXmlField = value;
            }
        }
        
        /// <remarks/>
        public bool MoreDocs {
            get {
                return this.moreDocsField;
            }
            set {
                this.moreDocsField = value;
            }
        }
        
        /// <remarks/>
        public int LastIdVisited {
            get {
                return this.lastIdVisitedField;
            }
            set {
                this.lastIdVisitedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssResolveSPGroupResult : GssAclBaseResult {
        
        private GssPrincipal[] prinicpalsField;
        
        /// <remarks/>
        public GssPrincipal[] Prinicpals {
            get {
                return this.prinicpalsField;
            }
            set {
                this.prinicpalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetAclChangesSinceTokenResult : GssAclBaseResult {
        
        private GssAclChangeCollection allChangesField;
        
        /// <remarks/>
        public GssAclChangeCollection AllChanges {
            get {
                return this.allChangesField;
            }
            set {
                this.allChangesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void CheckConnectivityCompletedEventHandler(object sender, CheckConnectivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckConnectivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckConnectivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetAclForUrlsCompletedEventHandler(object sender, GetAclForUrlsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAclForUrlsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAclForUrlsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GssGetAclForUrlsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GssGetAclForUrlsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetAclChangesSinceTokenCompletedEventHandler(object sender, GetAclChangesSinceTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAclChangesSinceTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAclChangesSinceTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GssGetAclChangesSinceTokenResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GssGetAclChangesSinceTokenResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ResolveSPGroupCompletedEventHandler(object sender, ResolveSPGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResolveSPGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResolveSPGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GssResolveSPGroupResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GssResolveSPGroupResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetListsWithInheritingRoleAssignmentsCompletedEventHandler(object sender, GetListsWithInheritingRoleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListsWithInheritingRoleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListsWithInheritingRoleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetListItemsWithInheritingRoleAssignmentsCompletedEventHandler(object sender, GetListItemsWithInheritingRoleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListItemsWithInheritingRoleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListItemsWithInheritingRoleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GssGetListItemsWithInheritingRoleAssignments Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GssGetListItemsWithInheritingRoleAssignments)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591