//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4206.
// 
#pragma warning disable 1591

namespace WindowsApplication1.GSPSiteDiscoveryWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SiteDiscoverySoap", Namespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class SiteDiscovery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckConnectivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSiteCollectionFromAllWebAppsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebCrawlInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebCrawlInfoInBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListCrawlInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCrawlableListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SiteDiscovery() {
            this.Url = global::WindowsApplication1.Properties.Settings.Default.Verify_Installation_GSPSiteDiscoveryWS_SiteDiscovery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckConnectivityCompletedEventHandler CheckConnectivityCompleted;
        
        /// <remarks/>
        public event GetAllSiteCollectionFromAllWebAppsCompletedEventHandler GetAllSiteCollectionFromAllWebAppsCompleted;
        
        /// <remarks/>
        public event GetWebCrawlInfoCompletedEventHandler GetWebCrawlInfoCompleted;
        
        /// <remarks/>
        public event GetWebCrawlInfoInBatchCompletedEventHandler GetWebCrawlInfoInBatchCompleted;
        
        /// <remarks/>
        public event GetListCrawlInfoCompletedEventHandler GetListCrawlInfoCompleted;
        
        /// <remarks/>
        public event IsCrawlableListCompletedEventHandler IsCrawlableListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/CheckConnect" +
            "ivity", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckConnectivity() {
            object[] results = this.Invoke("CheckConnectivity", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckConnectivityAsync() {
            this.CheckConnectivityAsync(null);
        }
        
        /// <remarks/>
        public void CheckConnectivityAsync(object userState) {
            if ((this.CheckConnectivityOperationCompleted == null)) {
                this.CheckConnectivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckConnectivityOperationCompleted);
            }
            this.InvokeAsync("CheckConnectivity", new object[0], this.CheckConnectivityOperationCompleted, userState);
        }
        
        private void OnCheckConnectivityOperationCompleted(object arg) {
            if ((this.CheckConnectivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckConnectivityCompleted(this, new CheckConnectivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/GetAllSiteCo" +
            "llectionFromAllWebApps", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetAllSiteCollectionFromAllWebApps() {
            object[] results = this.Invoke("GetAllSiteCollectionFromAllWebApps", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSiteCollectionFromAllWebAppsAsync() {
            this.GetAllSiteCollectionFromAllWebAppsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSiteCollectionFromAllWebAppsAsync(object userState) {
            if ((this.GetAllSiteCollectionFromAllWebAppsOperationCompleted == null)) {
                this.GetAllSiteCollectionFromAllWebAppsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSiteCollectionFromAllWebAppsOperationCompleted);
            }
            this.InvokeAsync("GetAllSiteCollectionFromAllWebApps", new object[0], this.GetAllSiteCollectionFromAllWebAppsOperationCompleted, userState);
        }
        
        private void OnGetAllSiteCollectionFromAllWebAppsOperationCompleted(object arg) {
            if ((this.GetAllSiteCollectionFromAllWebAppsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSiteCollectionFromAllWebAppsCompleted(this, new GetAllSiteCollectionFromAllWebAppsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/GetWebCrawlI" +
            "nfo", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebCrawlInfo GetWebCrawlInfo() {
            object[] results = this.Invoke("GetWebCrawlInfo", new object[0]);
            return ((WebCrawlInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebCrawlInfoAsync() {
            this.GetWebCrawlInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetWebCrawlInfoAsync(object userState) {
            if ((this.GetWebCrawlInfoOperationCompleted == null)) {
                this.GetWebCrawlInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebCrawlInfoOperationCompleted);
            }
            this.InvokeAsync("GetWebCrawlInfo", new object[0], this.GetWebCrawlInfoOperationCompleted, userState);
        }
        
        private void OnGetWebCrawlInfoOperationCompleted(object arg) {
            if ((this.GetWebCrawlInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebCrawlInfoCompleted(this, new GetWebCrawlInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/GetWebCrawlI" +
            "nfoInBatch", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebCrawlInfo[] GetWebCrawlInfoInBatch(string[] webUrls) {
            object[] results = this.Invoke("GetWebCrawlInfoInBatch", new object[] {
                        webUrls});
            return ((WebCrawlInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWebCrawlInfoInBatchAsync(string[] webUrls) {
            this.GetWebCrawlInfoInBatchAsync(webUrls, null);
        }
        
        /// <remarks/>
        public void GetWebCrawlInfoInBatchAsync(string[] webUrls, object userState) {
            if ((this.GetWebCrawlInfoInBatchOperationCompleted == null)) {
                this.GetWebCrawlInfoInBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebCrawlInfoInBatchOperationCompleted);
            }
            this.InvokeAsync("GetWebCrawlInfoInBatch", new object[] {
                        webUrls}, this.GetWebCrawlInfoInBatchOperationCompleted, userState);
        }
        
        private void OnGetWebCrawlInfoInBatchOperationCompleted(object arg) {
            if ((this.GetWebCrawlInfoInBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebCrawlInfoInBatchCompleted(this, new GetWebCrawlInfoInBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/GetListCrawl" +
            "Info", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListCrawlInfo[] GetListCrawlInfo(string[] listGuids) {
            object[] results = this.Invoke("GetListCrawlInfo", new object[] {
                        listGuids});
            return ((ListCrawlInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListCrawlInfoAsync(string[] listGuids) {
            this.GetListCrawlInfoAsync(listGuids, null);
        }
        
        /// <remarks/>
        public void GetListCrawlInfoAsync(string[] listGuids, object userState) {
            if ((this.GetListCrawlInfoOperationCompleted == null)) {
                this.GetListCrawlInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListCrawlInfoOperationCompleted);
            }
            this.InvokeAsync("GetListCrawlInfo", new object[] {
                        listGuids}, this.GetListCrawlInfoOperationCompleted, userState);
        }
        
        private void OnGetListCrawlInfoOperationCompleted(object arg) {
            if ((this.GetListCrawlInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCrawlInfoCompleted(this, new GetListCrawlInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("gssitediscovery.generated.sharepoint.connector.enterprise.google.com/IsCrawlableL" +
            "ist", RequestNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", ResponseNamespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsCrawlableList(string listGUID) {
            object[] results = this.Invoke("IsCrawlableList", new object[] {
                        listGUID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsCrawlableListAsync(string listGUID) {
            this.IsCrawlableListAsync(listGUID, null);
        }
        
        /// <remarks/>
        public void IsCrawlableListAsync(string listGUID, object userState) {
            if ((this.IsCrawlableListOperationCompleted == null)) {
                this.IsCrawlableListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCrawlableListOperationCompleted);
            }
            this.InvokeAsync("IsCrawlableList", new object[] {
                        listGUID}, this.IsCrawlableListOperationCompleted, userState);
        }
        
        private void OnIsCrawlableListOperationCompleted(object arg) {
            if ((this.IsCrawlableListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCrawlableListCompleted(this, new IsCrawlableListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com")]
    public partial class ListCrawlInfo {
        
        private string listGuidField;
        
        private bool noCrawlField;
        
        private bool statusField;
        
        private string errorField;
        
        /// <remarks/>
        public string ListGuid {
            get {
                return this.listGuidField;
            }
            set {
                this.listGuidField = value;
            }
        }
        
        /// <remarks/>
        public bool NoCrawl {
            get {
                return this.noCrawlField;
            }
            set {
                this.noCrawlField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssitediscovery.generated.sharepoint.connector.enterprise.google.com")]
    public partial class WebCrawlInfo {
        
        private string webKeyField;
        
        private bool crawlAspxPagesField;
        
        private bool noCrawlField;
        
        private bool statusField;
        
        private string errorField;
        
        /// <remarks/>
        public string WebKey {
            get {
                return this.webKeyField;
            }
            set {
                this.webKeyField = value;
            }
        }
        
        /// <remarks/>
        public bool CrawlAspxPages {
            get {
                return this.crawlAspxPagesField;
            }
            set {
                this.crawlAspxPagesField = value;
            }
        }
        
        /// <remarks/>
        public bool NoCrawl {
            get {
                return this.noCrawlField;
            }
            set {
                this.noCrawlField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void CheckConnectivityCompletedEventHandler(object sender, CheckConnectivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckConnectivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckConnectivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetAllSiteCollectionFromAllWebAppsCompletedEventHandler(object sender, GetAllSiteCollectionFromAllWebAppsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSiteCollectionFromAllWebAppsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSiteCollectionFromAllWebAppsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetWebCrawlInfoCompletedEventHandler(object sender, GetWebCrawlInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebCrawlInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebCrawlInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebCrawlInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebCrawlInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetWebCrawlInfoInBatchCompletedEventHandler(object sender, GetWebCrawlInfoInBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebCrawlInfoInBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebCrawlInfoInBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebCrawlInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebCrawlInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetListCrawlInfoCompletedEventHandler(object sender, GetListCrawlInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCrawlInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCrawlInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListCrawlInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListCrawlInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void IsCrawlableListCompletedEventHandler(object sender, IsCrawlableListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCrawlableListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCrawlableListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591